version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - mimir
      - loki
      - tempo

  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir/mimir.yaml"]
    volumes:
      - ./config/mimir:/etc/mimir
    ports:
      - "9009:9009"
    restart: always
    environment:
      - BASIC_AUTH_USER=${MIMIR_USER}
      - BASIC_AUTH_PASS=${MIMIR_PASSWORD}

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./config/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: always
    environment:
      - BASIC_AUTH_USER=${LOKI_USER}
      - BASIC_AUTH_PASS=${LOKI_PASSWORD}

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./config/tempo:/etc/tempo
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3200:3200"
    restart: always
    environment:
      - BASIC_AUTH_USER=${TEMPO_USER}
      - BASIC_AUTH_PASS=${TEMPO_PASSWORD}

  alloy:
    image: grafana/alloy:latest
    command: ["--config.file=/etc/alloy/config.alloy"]
    network_mode: "host"
    volumes:
      - ./config/alloy:/etc/alloy
      - /var/log:/var/log
    restart: always

volumes:
  grafana-storage:
